defmodule Rumbo.Repo.Migrations.PartitionPositions do
  use Ecto.Migration

  @moduledoc """
  Reconstruye `positions` como tabla particionada por rango de `recorded_at`
  (una partición por mes). A volúmenes altos esto mantiene índices pequeños y
  permite descartar histórico antiguo con DROP de partición en vez de DELETE.

  La partición DEFAULT recoge cualquier fecha sin partición propia (colas
  offline con recorded_at antiguos). PartitionManager crea las particiones
  mensuales futuras en runtime; aquí se crean las del mes actual ± 2 para que
  el primer boot no dependa de él.
  """

  def up do
    execute "DROP TABLE positions"

    execute """
    CREATE TABLE positions (
      id bigint GENERATED BY DEFAULT AS IDENTITY,
      project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      tracker_id uuid NOT NULL REFERENCES trackers(id) ON DELETE CASCADE,
      trip_id uuid REFERENCES trips(id) ON DELETE SET NULL,
      lat float8 NOT NULL,
      lng float8 NOT NULL,
      speed float8,
      heading float8,
      accuracy float8,
      altitude float8,
      battery float8,
      metadata jsonb,
      recorded_at timestamptz NOT NULL,
      inserted_at timestamptz NOT NULL DEFAULT now(),
      PRIMARY KEY (id, recorded_at)
    ) PARTITION BY RANGE (recorded_at)
    """

    # El índice único (dedupe de ingest) incluye la partition key, requisito
    # de Postgres para ON CONFLICT sobre tablas particionadas.
    execute "CREATE UNIQUE INDEX positions_tracker_id_recorded_at_index ON positions (tracker_id, recorded_at)"
    execute "CREATE INDEX positions_project_id_index ON positions (project_id)"
    execute "CREATE INDEX positions_trip_id_index ON positions (trip_id)"

    execute "CREATE TABLE positions_default PARTITION OF positions DEFAULT"

    for offset <- -2..2 do
      {name, from, to} = month_partition(offset)

      execute "CREATE TABLE IF NOT EXISTS #{name} PARTITION OF positions FOR VALUES FROM ('#{from}') TO ('#{to}')"
    end
  end

  def down do
    execute "DROP TABLE positions"

    execute """
    CREATE TABLE positions (
      id bigserial PRIMARY KEY,
      project_id uuid NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
      tracker_id uuid NOT NULL REFERENCES trackers(id) ON DELETE CASCADE,
      trip_id uuid REFERENCES trips(id) ON DELETE SET NULL,
      lat float8 NOT NULL,
      lng float8 NOT NULL,
      speed float8,
      heading float8,
      accuracy float8,
      altitude float8,
      battery float8,
      metadata jsonb,
      recorded_at timestamptz NOT NULL,
      inserted_at timestamptz NOT NULL DEFAULT now()
    )
    """

    execute "CREATE UNIQUE INDEX positions_tracker_id_recorded_at_index ON positions (tracker_id, recorded_at)"
    execute "CREATE INDEX positions_project_id_index ON positions (project_id)"
    execute "CREATE INDEX positions_trip_id_index ON positions (trip_id)"
  end

  defp month_partition(month_offset) do
    first = Date.utc_today() |> Date.beginning_of_month() |> Date.shift(month: month_offset)
    next = Date.shift(first, month: 1)
    name = "positions_y#{first.year}m#{String.pad_leading(to_string(first.month), 2, "0")}"
    {name, Date.to_iso8601(first), Date.to_iso8601(next)}
  end
end
